// <auto-generated />
namespace JabbR.Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class UserIsBanned : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207241552024_UserIsBanned"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9kk8mrsbT7KD0ui4xweJ2X5++J0M5DIPSR7Yo6OyWk2us316ucO/zso5N51p6URb5s/XbU8vfKr4MP6KOXdbXK6/b6VX6ub1Ojj9K74Yt3u2/a9/yXgMJnH50t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27ymaTmb5TwEJcWj1ae3o8bDuzt7oMbdbLms2qylOe5h3sHzbGbQfN3WxCwfpc+Kd/nseb68aOcW1S+yd+YT+vWj9KtlQbxFL7X1OveHJn9v7vKrJq+PLzAZP+yen2dNezxti0umrXT+lCj/hnj4y/PzJm8j03TzYG4x1x0gL7LL4oLnJwLuo/RVXvKXzbxYiVCMHQv//tLmWV0tXlXoovPV7/+6WtdT6vNNFf/+TVZfYKQ+To/vOqG5UZQYgR8J0gcKEnXzgeyMf9+z0w+XoW9nzfyH3unrrPzhawuMFLzUNFdV/b6z++Hdb1JWN2uYCLAX69lFbscRA3UbtF6TOKyb99R3Xcat2vdl3A+XluPztz8n/Z411LPp9UlFKjlbvjfFnpXZxfti/qF4W935Xt1+OOOfLrKi/KH3StM0WxTLD52os+YJ2QwnZreGM+gSkFO9zKdk1cSGNx/qHhjzP+QeGPfhtvh9eUXDfVVV"
                       + "i2HM8O3vj3Z108XM+yqKmf/9+2J2C6Qw4jhO/M0wSvL1+2J0XJbV1a2opS2H8fMbDKMZtIph+16OH0D+yPH7WTOtX8Of+3DzdFJWzddQVx0ob6pVMX1P3A8+FPXv5iVN3Q+fZC/r4jJznsTXpdnZkly7/ITQ2DgCwcgbwKcfiP5JnWckNZvkKwrmJq2muuqb02qxQHZY990WWx3+ZkRtowiO+t0weqbB+2JmLOSHWdFBtDpW9rZYfZE3TXaRD+OlDX5/tg4dxPzvolYqaPC+5vQWHHeTgR+k1jBzvZfJ1PH9yGr2vdr25yIF+N5pmg/v8rvz3IYVH5htBGf2Z/j90LkpY/l+ul+E/kM1Q0wKo6rjtmhtzKMayLFIyf9uI1rvnUo9bppqWjA+HZc6NIvhCE+Xs/RWNlJ42td9xMbrsi1WZTEldD776Fs98t0E3CrsELjQbSPwx3e94d6SCsbm3ohjzwB/Q2Pv2u1bDHtnPN7tgSYVntfQpFlJaq5p66xYtn19XyynxSorb8Ci895tLQWmwHbR/eZpvsqX0PU3UPY2ffveZB8F21PHjN1Eoq/DP+oa3TjNXT/pG+KebhLjZub5MJkJlOsm7OKaNkTPuCnvOfC4e3czQb9ZsYlhcRvW/SbEJkbc2/RtLfk3IDMW86/FP5HVvPgkhybxG+WfMDF5s+T87PCPj8Vt5vCb5B+fuLfp23pxP2f844VXN+rGnx1f5YfspPj59U24RdfiQ+SkyfsOOprFv3nUu12Gevzl8mle5m2eYn2xosDvJGumGfJQ3XCTEPiGhCyC/G34/JuQsciE3KbrH6aISciAoJjeyGvF4DvZZFJzpPyuQy194XXeGgY1i0Mu+IjwW4+9QiCaLImCEM66AQDEcgiAiPkNAFyyKQrDmpkOGI+qHkmMngizjl7bjenJ7qTfNhKzQ7Lk6PHPbeMuD5Qi35XPcODvQxSb4dxAj2hEFse/G5N9PSp0I7CfTQKYTOqG8cci"
                       + "ijjinZji642+E0H8LA0+TMrERz8cW/Qwj0YXHupOom8gQTSWuImQH0gDUWqbadC394OoByb/Q2gQmPifJT7w/LdNMnBrZfhNaMEfivrz/biBkQ+6ej20Y86eh7c1yzeMPubafcDwTQ7SOhT2u8d3X3MmXz94fJeaTPNVu87KLyjDXTbmiy+y1Yry4+Zv90n6epVNgfb2a10nuN0iwcFdWidYCIy704Cluu6P7YlsAYlD51vqmjB9VtRNS+n0bJIhb34yW/Sa3cZ9Ml2FXlR/sowzYtrjd+ekvRoL8XxnqwPDEfAZjWlBLXh4Ojhhlg0v0+uvp1mZ1bH1npOqXC+WGxzm4fexHuK/jr9v/zb48vgCCAdAvI9vD+t51rSIR2hR/DoEF35ze4jWge/i9vsPEOnx3c4UdfnAS+1ry45EdvnqVlw3pGLfg+dimuqWHBd/9f+d/IZ/w/flk9tD+HbWzEMI8sntIbzOyg67yye3h4AeseraNFdV3aFH97vbQ/3m5QfvvVjPLvIOjv7nt4f2mhaG102HcvrZ7aG8qNouB/Ant4dwfP62D8R+eHs4Zw291GFm+ej2MJ6V2UUIQj65PQS3ZB9Klfn09pBOF1lRhmD0o9vDIALMFsWyRxX58H3gPMmWyy7fuU//X6O6xbf9INUdi7Fuqbrjr/5sqe5vVh3g3w9T5Sdl1XRxMZ/dHsqbalVMQyD60e1hfDcvydHtDMd+eHs4lNW8zLqqyX54ezhnS1L1ObzkjgB5n98emr/CG9BakzX/73KmbKz9QUJpEo1fTy4H3/7ZEk0OcrpeuP3w9nA+zDv77jzvqH755PYQoNB6tODMwHsS5P91rn8YqneiTpP+CBPVN9iMTush+zDk4iMB0eWiGOThFZPbcbIFOrCU4qHxdTF8M7ScdHsMh1ljGMNu/uXrz7tJRd8046ZdZ657c91f8dtAyjB1/SFE/OanOcyIfwhuP7cTfEuJvqUo773P9P6/WIj/Xy69"
                       + "vSRqt4m1GfqJ/dsmUTWBKfPs3pMULI+o0WRqN6MpTT5KCffLYoZs5uvrps0XYzQYv/5FpVnSNQ2+yJbFed60b6q3OaWykXCl7HZZZI3ktd8rV/vw7s7e3Xy2uNs0szKSqQUje7MZS1o+pvnoToaZiI3L+4/vdt+07/kvycpwARKwvHye0wyRn0y5k7bN6yWcFxMEv1iXZTZBrv08K5ue89uFD69HwC8vs3o6z+qtRfbujg+nrdc3gvGyoN8AtDCJIwBnNN62WOTV+XlDIvS+43Ri4xFzIwzfC7qRK/pex/+veOKj9Ivs3fN8edHOWdzed0Lx7zfCGd/mBOY3wGKvOY/5DQDqJjG/AZCb2P+9J9PPWAyDug1aJoF5WwGKsAGnHb9Z1rLZzG8WrKY3BeikeP+xSnJzE1LvjZKV52+AxzTd+Q1AsinPr08rl+y8LYz3Us791OH/h5XzNyfPMaX8oWJjcpK3ncc+BE1IbkDr4L2xsunJb3awNlv59UfrZykVuR5mn74vXkGyMqqt+1DeS6CiOb//D8uUzR5+E+rwm/EBJJsYCvjXdH1dMHtLXuiDuMF7/kB2Gk7d3Y6nbojY4y8MxdE3c2PY3df3hkIsbgvna1O2kyj7EWm/OdJ2klQ/Iu2tSevlpTz4kmPhnFmHspThSl9VpYeHwQF5n7H78It12RarsphSp5991E8Sf7l8mpd5m6cItCoyHidZM81m/eEjqbYJB5Ob6mBhPg7x+FYPPE1vXsNsZSVZoaatKfvWW48hR2M5LVZZ2R17p2GUbeLsddfC7H7zNF/lS1jS/iBv092m/KQF3SHxTUQI8pc3sw+zuTpB3wz/7IzHu72pC2FxkNGFJR/+/4MH+lEUN43oqU1r5T80JlAf9fePBH9fc+JuwQTGMe6Cs5//rLHCrWfnm2CFwTX/SH+bllIs7B8OK3xz9uT/1azwQ9UK78MK/28xDTcu+X9dDfGz6GYEMVIMlyFW/QYZ64eqY+JB"
                       + "YTrcqZ3e/7dxWGzR9+sqnv+fc9gPVXV9LQ77f4sO+/Jq+f9R7bW7kbl2fxa56+dMf/UoO8he/29RYMpe/x9UXT937HVrPfJzx17/b9Fe/591vfY2ctfezyJ3/Zwpr05yk9/5f7fy+v+s2/Vzx10/Z7rr9tz1Q9Vdp5ytxrogvZHXBg1ap31W1E37NGuzSdb0dRfeep23vVz2R6l8N5Alfj2d54uMVvomFbGAZNHd900k1dDvSPg22o18NdQJi8utuhDFG+1CvhrqAt/ergubHon2Yr8d6kgb3K6vMKgZHNbNFOx4GO/Z9e4t+t69XefvP+69W3S+t5l3hifYE66YUEhCLvVa9UQjkrMb0OJ2oP6HPU0RvhnKpn3XfNzV5OFwbjlUtkhmMWJgrEGbn63B+sJr35QPv5GBBgn3gYEOJ+W/Prq9NzsqxL5sP/9Gh7uJh4cTz9/gvP5whsssGkucbmLpGxOt3+Csx5R5AGGIoN8YQdThvDVBYg7qN8gXPycECdNSm0ixIYH1s8QV1s5GqdC32x9OhltwxIZEy88SL/wQyXBrRXFbDfGN8YJ1e6JE2PvmiXALVviha4VvjgiIcgHIBkz2u8d3xXXUD+hP8nHILH1BoVTZ8KcUpq3p7UUufz3Nm+LCgXhMMJc5B9kOqGlztjyvTLTYwcg0MV/rtHyRt9mMorfjui3Os2lLX0/JUBbLi4/Sn8zKNTU5XUzy2dnyy3W7Wrc05HwxKYOoE/Hmpv4f3+3h/PjLFf5qvokhEJoFDSH/cvlkXZQzi/ezrGw65n4IBALZz3P6XOaS4uI2v7i2kF5Uy1sCUvI9NfH3m3yxKglY8+XydXaZD+N2Mw1Dij1+WmQXdbZoFIZ7n/4k9pst3h39PwEAAP//L5s+vBx8AAA="; }
        }
    }
}
