//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JabbR.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JabbR.Resources.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alt + L ähnelt.
        /// </summary>
        public static string AltPlusL {
            get {
                return ResourceManager.GetString("AltPlusL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alt + Number ähnelt.
        /// </summary>
        public static string AltPlusNumber {
            get {
                return ResourceManager.GetString("AltPlusNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A password is required. ähnelt.
        /// </summary>
        public static string APasswordIsRequired {
            get {
                return ResourceManager.GetString("APasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die but it&apos;s closed ähnelt.
        /// </summary>
        public static string AppendButItsClosed {
            get {
                return ResourceManager.GetString("AppendButItsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die at ähnelt.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audible Notifications ähnelt.
        /// </summary>
        public static string AudibleNotifications {
            get {
                return ResourceManager.GetString("AudibleNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click on a user to send message. ähnelt.
        /// </summary>
        public static string ClickOnAUserToSendMessage {
            get {
                return ResourceManager.GetString("ClickOnAUserToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (click to show/hide) ähnelt.
        /// </summary>
        public static string ClickToShowHide {
            get {
                return ResourceManager.GetString("ClickToShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deployed from ähnelt.
        /// </summary>
        public static string DeployedFrom {
            get {
                return ResourceManager.GetString("DeployedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display help ähnelt.
        /// </summary>
        public static string DisplayHelp {
            get {
                return ResourceManager.GetString("DisplayHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Messages ähnelt.
        /// </summary>
        public static string DownloadMessages {
            get {
                return ResourceManager.GetString("DownloadMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email is required ähnelt.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email was not specified! ähnelt.
        /// </summary>
        public static string EmailWasNotSpecified {
            get {
                return ResourceManager.GetString("EmailWasNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FAQ ähnelt.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to specific Tab. ähnelt.
        /// </summary>
        public static string GoToSpecificTab {
            get {
                return ResourceManager.GetString("GoToSpecificTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to the Lobby. ähnelt.
        /// </summary>
        public static string GoToTheLobby {
            get {
                return ResourceManager.GetString("GoToTheLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to the next open room tab or Go to the previous open room tab. ähnelt.
        /// </summary>
        public static string GoToTheNextOpenRoomTabOrGoToThePreviousOpenRoomTab {
            get {
                return ResourceManager.GetString("GoToTheNextOpenRoomTabOrGoToThePreviousOpenRoomTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gravatar Profile ähnelt.
        /// </summary>
        public static string GravatarProfile {
            get {
                return ResourceManager.GetString("GravatarProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identity {0} already taken with Provider {1}, please login with a different provider/identity combination. ähnelt.
        /// </summary>
        public static string IdentityXAlreadyTakenWithProviderYPleaseLoginWithADifferentProviderIdentityCombination {
            get {
                return ResourceManager.GetString("IdentityXAlreadyTakenWithProviderYPleaseLoginWithADifferentProviderIdentityCombin" +
                        "ation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die if you don&apos;t have an account. ähnelt.
        /// </summary>
        public static string IfYouDontHaveAnAccount {
            get {
                return ResourceManager.GetString("IfYouDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invite Code for this room: {0} ähnelt.
        /// </summary>
        public static string InviteCodeForThisRoomX {
            get {
                return ResourceManager.GetString("InviteCodeForThisRoomX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invite them to which room? ähnelt.
        /// </summary>
        public static string InviteThemToWhichRoom {
            get {
                return ResourceManager.GetString("InviteThemToWhichRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is assigned ähnelt.
        /// </summary>
        public static string IsAssigned {
            get {
                return ResourceManager.GetString("IsAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join which room? ähnelt.
        /// </summary>
        public static string JoinWhichRoom {
            get {
                return ResourceManager.GetString("JoinWhichRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last day ähnelt.
        /// </summary>
        public static string LastDay {
            get {
                return ResourceManager.GetString("LastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last hour ähnelt.
        /// </summary>
        public static string LastHour {
            get {
                return ResourceManager.GetString("LastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last month ähnelt.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last week ähnelt.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List users in which room? ähnelt.
        /// </summary>
        public static string ListUsersInWhichRoom {
            get {
                return ResourceManager.GetString("ListUsersInWhichRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lobby is not a valid chat room. ähnelt.
        /// </summary>
        public static string LobbyIsNotAValidChatRoom {
            get {
                return ResourceManager.GetString("LobbyIsNotAValidChatRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed. Check your username/password. ähnelt.
        /// </summary>
        public static string LoginFailedCheckYourUsernamePassword {
            get {
                return ResourceManager.GetString("LoginFailedCheckYourUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing password ähnelt.
        /// </summary>
        public static string MissingPassword {
            get {
                return ResourceManager.GetString("MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing username ähnelt.
        /// </summary>
        public static string MissingUsername {
            get {
                return ResourceManager.GetString("MissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No milestone ähnelt.
        /// </summary>
        public static string NoMilestone {
            get {
                return ResourceManager.GetString("NoMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No room specified. ähnelt.
        /// </summary>
        public static string NoRoomSpecified {
            get {
                return ResourceManager.GetString("NoRoomSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nudged {0} ähnelt.
        /// </summary>
        public static string NudgedX {
            get {
                return ResourceManager.GetString("NudgedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old password is required. ähnelt.
        /// </summary>
        public static string OldPasswordIsRequired {
            get {
                return ResourceManager.GetString("OldPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on ähnelt.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only private rooms can have invite codes. ähnelt.
        /// </summary>
        public static string OnlyPrivateRoomsCanHaveInviteCodes {
            get {
                return ResourceManager.GetString("OnlyPrivateRoomsCanHaveInviteCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die opened this issue ähnelt.
        /// </summary>
        public static string OpenedThisIssue {
            get {
                return ResourceManager.GetString("OpenedThisIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owners cannot kick other owners. Only the room creator can kick an owner. ähnelt.
        /// </summary>
        public static string OwnersCannotKickOtherOwnersOnlyTheRoomCreatorCanKickAnOwner {
            get {
                return ResourceManager.GetString("OwnersCannotKickOtherOwnersOnlyTheRoomCreatorCanKickAnOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owners cannot unallow other owners. Only the room creator can unallow an owner. ähnelt.
        /// </summary>
        public static string OwnersCannotUnallowOtherOwnersOnlyTheRoomCreatorCanUnallowAnOwner {
            get {
                return ResourceManager.GetString("OwnersCannotUnallowOtherOwnersOnlyTheRoomCreatorCanUnallowAnOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password is required ähnelt.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwords don&apos;t match. ähnelt.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste (click to show/hide) ähnelt.
        /// </summary>
        public static string PasteClickToShowHide {
            get {
                return ResourceManager.GetString("PasteClickToShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Popup Notifications ähnelt.
        /// </summary>
        public static string PopupNotifications {
            get {
                return ResourceManager.GetString("PopupNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die range value not recognized ähnelt.
        /// </summary>
        public static string RangeValueNotRecognized {
            get {
                return ResourceManager.GetString("RangeValueNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh your browser to get the latest. Auto update will take place in 15 seconds. ähnelt.
        /// </summary>
        public static string RefreshYourBrowserToGetTheLatestAutoUpdateWillTakePlaceIn15conds {
            get {
                return ResourceManager.GetString("RefreshYourBrowserToGetTheLatestAutoUpdateWillTakePlaceIn15conds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room can only be nudged once every {0} seconds ähnelt.
        /// </summary>
        public static string RoomCanOnlyBeNudgedOnceEveryXSeconds {
            get {
                return ResourceManager.GetString("RoomCanOnlyBeNudgedOnceEveryXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room commands ähnelt.
        /// </summary>
        public static string RoomCommands {
            get {
                return ResourceManager.GetString("RoomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room name cannot be blank! ähnelt.
        /// </summary>
        public static string RoomNameCannotBeBlank {
            get {
                return ResourceManager.GetString("RoomNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room name cannot contain spaces. ähnelt.
        /// </summary>
        public static string RoomNameCannotContainSpaces {
            get {
                return ResourceManager.GetString("RoomNameCannotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select date range for messages ähnelt.
        /// </summary>
        public static string SelectDateRangeForMessages {
            get {
                return ResourceManager.GetString("SelectDateRangeForMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send ähnelt.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Closed Rooms? ähnelt.
        /// </summary>
        public static string ShowClosedRooms {
            get {
                return ResourceManager.GetString("ShowClosedRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in ähnelt.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site wide commands ähnelt.
        /// </summary>
        public static string SiteWideCommands {
            get {
                return ResourceManager.GetString("SiteWideCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site wide shortcuts ähnelt.
        /// </summary>
        public static string SiteWideShortcuts {
            get {
                return ResourceManager.GetString("SiteWideShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but the country ISO code you requested doesn&apos;t exist. Please refer to http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 for a proper list of country ISO codes. ähnelt.
        /// </summary>
        public static string SorryButTheCountryISOCodeYouRequestedDoesntExistPleaseReferToUrlForAProperListOfCountryISOCodes {
            get {
                return ResourceManager.GetString("SorryButTheCountryISOCodeYouRequestedDoesntExistPleaseReferToUrlForAProperListOfC" +
                        "ountryISOCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but your {1} is too long. Can please keep it under {0} characters. ähnelt.
        /// </summary>
        public static string SorryButYourXIsTooLongCanPleaseKeepItUnderYCharacters {
            get {
                return ResourceManager.GetString("SorryButYourXIsTooLongCanPleaseKeepItUnderYCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully added a password. ähnelt.
        /// </summary>
        public static string SuccessfullyAddedAPassword {
            get {
                return ResourceManager.GetString("SuccessfullyAddedAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully changed your password. ähnelt.
        /// </summary>
        public static string SuccessfullyChangedYourPassword {
            get {
                return ResourceManager.GetString("SuccessfullyChangedYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully changed your username. ähnelt.
        /// </summary>
        public static string SuccessfullyChangedYourUsername {
            get {
                return ResourceManager.GetString("SuccessfullyChangedYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully linked {0} account. ähnelt.
        /// </summary>
        public static string SuccessfullyLinkedXAccount {
            get {
                return ResourceManager.GetString("SuccessfullyLinkedXAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully unlinked {0} account. ähnelt.
        /// </summary>
        public static string SuccessfullyUnlinkedXAccount {
            get {
                return ResourceManager.GetString("SuccessfullyUnlinkedXAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab or Shift + Tab ähnelt.
        /// </summary>
        public static string TabOrShiftPlusTab {
            get {
                return ResourceManager.GetString("TabOrShiftPlusTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die That&apos;s already your username... ähnelt.
        /// </summary>
        public static string ThatsAlreadyYourUsername {
            get {
                return ResourceManager.GetString("ThatsAlreadyYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error contacting the server, please refresh in a few minutes. ähnelt.
        /// </summary>
        public static string ThereWasAnErrorContactingTheServerPleaseRefreshInAFewMinutes {
            get {
                return ResourceManager.GetString("ThereWasAnErrorContactingTheServerPleaseRefreshInAFewMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The room &apos;{0}&apos; already exists{1} ähnelt.
        /// </summary>
        public static string TheRoomXAlreadyExistsAppend {
            get {
                return ResourceManager.GetString("TheRoomXAlreadyExistsAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The room &apos;{0}&apos; is closed. ähnelt.
        /// </summary>
        public static string TheRoomXIsClosed {
            get {
                return ResourceManager.GetString("TheRoomXIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This {0} account has already been linked to another user. ähnelt.
        /// </summary>
        public static string ThisXAccountHasAlreadyBeenLinkedToAnotherUser {
            get {
                return ResourceManager.GetString("ThisXAccountHasAlreadyBeenLinkedToAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Rich-content ähnelt.
        /// </summary>
        public static string ToggleRichContent {
            get {
                return ResourceManager.GetString("ToggleRichContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type @@ then press TAB to auto-complete nicknames ähnelt.
        /// </summary>
        public static string TypeAtAtThenPressTABToAutoCompleteNicknames {
            get {
                return ResourceManager.GetString("TypeAtAtThenPressTABToAutoCompleteNicknames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type #roomname to create a link to a room ähnelt.
        /// </summary>
        public static string TypeRoomnameToCreateALinkToARoom {
            get {
                return ResourceManager.GetString("TypeRoomnameToCreateALinkToARoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to find room &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string UnableToFindRoomX {
            get {
                return ResourceManager.GetString("UnableToFindRoomX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to find user &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string UnableToFindUserX {
            get {
                return ResourceManager.GetString("UnableToFindUserX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to join {0}. This room is locked and you don&apos;t have permission to enter. If you have an invite code, make sure to enter it in the /join command ähnelt.
        /// </summary>
        public static string UnableToJoinXThisRoomIsLockedAndYouDontHavePermissionToEnterIfYouHaveAnInviteCodeMakeSureToEnterItInTheJoinCommand {
            get {
                return ResourceManager.GetString("UnableToJoinXThisRoomIsLockedAndYouDontHavePermissionToEnterIfYouHaveAnInviteCode" +
                        "MakeSureToEnterItInTheJoinCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to locate room {0}. ähnelt.
        /// </summary>
        public static string UnableToLocateRoomX {
            get {
                return ResourceManager.GetString("UnableToLocateRoomX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use &apos;/join room&apos; to join a room. ähnelt.
        /// </summary>
        public static string UseJoinRoomToJoinARoom {
            get {
                return ResourceManager.GetString("UseJoinRoomToJoinARoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User can only be nudged once every {0} seconds ähnelt.
        /// </summary>
        public static string UserCanOnlyBeNudgedOnceEveryXSeconds {
            get {
                return ResourceManager.GetString("UserCanOnlyBeNudgedOnceEveryXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User commands ähnelt.
        /// </summary>
        public static string UserCommands {
            get {
                return ResourceManager.GetString("UserCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username is required. ähnelt.
        /// </summary>
        public static string UsernameIsRequired {
            get {
                return ResourceManager.GetString("UsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usernames don&apos;t match ähnelt.
        /// </summary>
        public static string UsernamesDontMatch {
            get {
                return ResourceManager.GetString("UsernamesDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username {0} already taken, please pick a new one using &apos;/nick nickname&apos;. ähnelt.
        /// </summary>
        public static string UsernameXAlreadyTakenPleasePickANewOneUsingNickNickname {
            get {
                return ResourceManager.GetString("UsernameXAlreadyTakenPleasePickANewOneUsingNickNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use #test for testing. ähnelt.
        /// </summary>
        public static string UseTestForTesting {
            get {
                return ResourceManager.GetString("UseTestForTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View the branch. ähnelt.
        /// </summary>
        public static string ViewTheBranch {
            get {
                return ResourceManager.GetString("ViewTheBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View the commit. ähnelt.
        /// </summary>
        public static string ViewTheCommit {
            get {
                return ResourceManager.GetString("ViewTheCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We didn&apos;t find anyone with the username {0} ähnelt.
        /// </summary>
        public static string WeDidntFindAnyoneWithTheUsername {
            get {
                return ResourceManager.GetString("WeDidntFindAnyoneWithTheUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What did you want to broadcast? ähnelt.
        /// </summary>
        public static string WhatDidYouWantToBroadcast {
            get {
                return ResourceManager.GetString("WhatDidYouWantToBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What did you want to say to &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string WhatDidYouWantToSayToX {
            get {
                return ResourceManager.GetString("WhatDidYouWantToSayToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which admin do you want to remove? ähnelt.
        /// </summary>
        public static string WhichAdminDoYouWantToRemove {
            get {
                return ResourceManager.GetString("WhichAdminDoYouWantToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which owner do you want to remove? ähnelt.
        /// </summary>
        public static string WhichOwnerDoYouWantToRemove {
            get {
                return ResourceManager.GetString("WhichOwnerDoYouWantToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which room? ähnelt.
        /// </summary>
        public static string WhichRoom {
            get {
                return ResourceManager.GetString("WhichRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which room do you want to lock? ähnelt.
        /// </summary>
        public static string WhichRoomDoYouWantToLock {
            get {
                return ResourceManager.GetString("WhichRoomDoYouWantToLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which room do you want to open? ähnelt.
        /// </summary>
        public static string WhichRoomDoYouWantToOpen {
            get {
                return ResourceManager.GetString("WhichRoomDoYouWantToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which user do you want to revoke permissions from? ähnelt.
        /// </summary>
        public static string WhichUserDoYouWantToRevokePersmissionsFrom {
            get {
                return ResourceManager.GetString("WhichUserDoYouWantToRevokePersmissionsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who are you trying send a private message to? ähnelt.
        /// </summary>
        public static string WhoAreYouTryingSendAPrivateMessageTo {
            get {
                return ResourceManager.GetString("WhoAreYouTryingSendAPrivateMessageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who are you trying to kick? ähnelt.
        /// </summary>
        public static string WhoAreYouTryingToKick {
            get {
                return ResourceManager.GetString("WhoAreYouTryingToKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who are you trying to locate? ähnelt.
        /// </summary>
        public static string WhoAreYouTryingToLocate {
            get {
                return ResourceManager.GetString("WhoAreYouTryingToLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who are you trying to ban? ähnelt.
        /// </summary>
        public static string WhoAreYouTtryingToBan {
            get {
                return ResourceManager.GetString("WhoAreYouTtryingToBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who do you want to allow? ähnelt.
        /// </summary>
        public static string WhoDoYouWantToAllow {
            get {
                return ResourceManager.GetString("WhoDoYouWantToAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who do you want to invite? ähnelt.
        /// </summary>
        public static string WhoDoYouWantToInvite {
            get {
                return ResourceManager.GetString("WhoDoYouWantToInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who do you want to make an admin? ähnelt.
        /// </summary>
        public static string WhoDoYouWantToMakeAnAdmin {
            get {
                return ResourceManager.GetString("WhoDoYouWantToMakeAnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who do you want to make an owner? ähnelt.
        /// </summary>
        public static string WhoDoYouWantToMakeAnOwner {
            get {
                return ResourceManager.GetString("WhoDoYouWantToMakeAnOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why would you want to kick yourself? ähnelt.
        /// </summary>
        public static string WhyWouldYouWantToKickYourself {
            get {
                return ResourceManager.GetString("WhyWouldYouWantToKickYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why would you want to unallow yourself? ähnelt.
        /// </summary>
        public static string WhyWouldYouWantToUnallowYourself {
            get {
                return ResourceManager.GetString("WhyWouldYouWantToUnallowYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is already allowed for &apos;{1}&apos;. ähnelt.
        /// </summary>
        public static string XIsAlreadyAllowedForY {
            get {
                return ResourceManager.GetString("XIsAlreadyAllowedForY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is already an admin. ähnelt.
        /// </summary>
        public static string XIsAlreadyAnAdmin {
            get {
                return ResourceManager.GetString("XIsAlreadyAnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is already an owner of &apos;{1}&apos;. ähnelt.
        /// </summary>
        public static string XIsAlreadyAnOwnerOfY {
            get {
                return ResourceManager.GetString("XIsAlreadyAnOwnerOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is already closed. ähnelt.
        /// </summary>
        public static string XIsAlreadyClosed {
            get {
                return ResourceManager.GetString("XIsAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is already locked. ähnelt.
        /// </summary>
        public static string XIsAlreadyLocked {
            get {
                return ResourceManager.GetString("XIsAlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is already open. ähnelt.
        /// </summary>
        public static string XIsAlreadyOpen {
            get {
                return ResourceManager.GetString("XIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is ambiguous: {1}. ähnelt.
        /// </summary>
        public static string XIsAmbiguousY {
            get {
                return ResourceManager.GetString("XIsAmbiguousY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not an admin. ähnelt.
        /// </summary>
        public static string XIsNotAnAdmin {
            get {
                return ResourceManager.GetString("XIsNotAnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not an owner of &apos;{1}&apos;. ähnelt.
        /// </summary>
        public static string XIsNotAnownerOfY {
            get {
                return ResourceManager.GetString("XIsNotAnownerOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not a private room. ähnelt.
        /// </summary>
        public static string XIsNotAPrivateRoom {
            get {
                return ResourceManager.GetString("XIsNotAPrivateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not a valid command. ähnelt.
        /// </summary>
        public static string XIsNotAValidCommand {
            get {
                return ResourceManager.GetString("XIsNotAValidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not a valid room name. ähnelt.
        /// </summary>
        public static string XIsNotAValidRoomName {
            get {
                return ResourceManager.GetString("XIsNotAValidRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is not a valid username. ähnelt.
        /// </summary>
        public static string XIsNotAValidUsername {
            get {
                return ResourceManager.GetString("XIsNotAValidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; isn&apos;t allowed to access &apos;{1}&apos;. ähnelt.
        /// </summary>
        public static string XIsntAllowedToAccessY {
            get {
                return ResourceManager.GetString("XIsntAllowedToAccessY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; isn&apos;t in &apos;{1}&apos;. ähnelt.
        /// </summary>
        public static string XIsntInY {
            get {
                return ResourceManager.GetString("XIsntInY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} nudged you ähnelt.
        /// </summary>
        public static string XNudgedYou {
            get {
                return ResourceManager.GetString("XNudgedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are not an admin. ähnelt.
        /// </summary>
        public static string YouAreNotAnAdmin {
            get {
                return ResourceManager.GetString("YouAreNotAnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are not an owner of room &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string YouAreNotAnOwnerOfRoomX {
            get {
                return ResourceManager.GetString("YouAreNotAnOwnerOfRoomX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are not the creator of &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string YouAreNotTheCreatorOfX {
            get {
                return ResourceManager.GetString("YouAreNotTheCreatorOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot ban another Admin. ähnelt.
        /// </summary>
        public static string YouCannotBanAnotherAdmin {
            get {
                return ResourceManager.GetString("YouCannotBanAnotherAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot kick an admin. Only admin can kick admin. ähnelt.
        /// </summary>
        public static string YouCannotKickAnAdminOnlyAdminCanKickAdmin {
            get {
                return ResourceManager.GetString("YouCannotKickAnAdminOnlyAdminCanKickAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot post messages to &apos;{0}&apos;. The room is closed. ähnelt.
        /// </summary>
        public static string YouCannotPostMessagesToXTheRoomIsClosed {
            get {
                return ResourceManager.GetString("YouCannotPostMessagesToXTheRoomIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot unallow an admin. Only admin can unallow admin. ähnelt.
        /// </summary>
        public static string YouCannotUnallowAnAdminOnlyAdminCanUnallowAdmin {
            get {
                return ResourceManager.GetString("YouCannotUnallowAnAdminOnlyAdminCanUnallowAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot unlink this account because you would lose your ability to login. ähnelt.
        /// </summary>
        public static string YouCannotUnlinkThisAccountBecauseYouWouldLoseYourAbilityToLogin {
            get {
                return ResourceManager.GetString("YouCannotUnlinkThisAccountBecauseYouWouldLoseYourAbilityToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t invite yourself! ähnelt.
        /// </summary>
        public static string YouCantInviteYourself {
            get {
                return ResourceManager.GetString("YouCantInviteYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t nudge yourself! ähnelt.
        /// </summary>
        public static string YouCantNudgeYourself {
            get {
                return ResourceManager.GetString("YouCantNudgeYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t private message yourself! ähnelt.
        /// </summary>
        public static string YouCantPrivateMessageYourself {
            get {
                return ResourceManager.GetString("YouCantPrivateMessageYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re in &apos;{0}&apos; but it doesn&apos;t exist. ähnelt.
        /// </summary>
        public static string YoureInXButItDoesntExist {
            get {
                return ResourceManager.GetString("YoureInXButItDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re not in &apos;{0}&apos;. Use &apos;/join {0}&apos; to join it. ähnelt.
        /// </summary>
        public static string YoureNotInXUseJoinXToJoinIt {
            get {
                return ResourceManager.GetString("YoureNotInXUseJoinXToJoinIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re not logged in. ähnelt.
        /// </summary>
        public static string YoureNotLoggedIn {
            get {
                return ResourceManager.GetString("YoureNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re the only person in here... ähnelt.
        /// </summary>
        public static string YoureTheOnlyPersonInHere {
            get {
                return ResourceManager.GetString("YoureTheOnlyPersonInHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password must be at least 6 characters. ähnelt.
        /// </summary>
        public static string YourPasswordMustBeAtLeast6Characters {
            get {
                return ResourceManager.GetString("YourPasswordMustBeAtLeast6Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You what? ähnelt.
        /// </summary>
        public static string YouWhat {
            get {
                return ResourceManager.GetString("YouWhat", resourceCulture);
            }
        }
    }
}
