using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using JabbR.Models;

namespace JabbR.Infrastructure
{
    using System.Collections;
    using System.Text;

    public class TextTransform
    {
        private readonly IJabbrRepository _repository;
        public const string HashTagPattern = @"(?:(?<=\s)|^)#([A-Za-z0-9-_.]{1,30}\w*)";

        public TextTransform(IJabbrRepository repository)
        {
            _repository = repository;
        }

        public string Parse(string message)
        {
            return ConvertTextWithNewLines(ConvertHashtagsToRoomLinks(message));
        }

        private string ConvertTextWithNewLines(string message)
        {
            // If the message contains new lines wrap all of it in a pre tag
            if (message.Contains('\n'))
            {
                return String.Format(@"
<div class=""collapsible_content"">
    <h3 class=""collapsible_title"">Paste (click to show/hide)</h3>
    <div class=""collapsible_box"">
        <pre class=""multiline"">{0}</pre>
    </div>
</div>
", message);
            }

            return message;
        }

        public static string TransformAndExtractUrls(string message, out HashSet<string> extractedUrls)
        {
            const string urlPattern = @"((https?|ftp)://|www\.)[\w]+(.[\w]+)([\w\-\.\[\],@?^=%&amp;:/~\+#!]*[\w\-\@?^=%&amp;/~\+#\[\]])";

            var urls = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            message = Regex.Replace(message, urlPattern, m =>
            {
                string httpPortion = String.Empty;
                if (!m.Value.Contains("://"))
                {
                    httpPortion = "http://";
                }

                string url = httpPortion + m.Value;

                urls.Add(HttpUtility.HtmlDecode(url));

                return String.Format(CultureInfo.InvariantCulture,
                                     "<a rel=\"nofollow external\" target=\"_blank\" href=\"{0}\" title=\"{1}\">{1}</a>",
                                     url, m.Value);
            });

            extractedUrls = urls;
            return message;
        }

        private string ConvertHashtagsToRoomLinks(string message)
        {
            message = Regex.Replace(message, HashTagPattern, m =>
            {
                //hashtag without #
                string roomName = m.Groups[1].Value;

                var room = _repository.GetRoomByName(roomName);

                if (room != null)
                {
                    return String.Format(CultureInfo.InvariantCulture,
                                         "<a href=\"#/rooms/{0}\" title=\"{1}\">{1}</a>",
                                         roomName,
                                         m.Value);
                }

                return m.Value;
            });

            return message;
        }

        public static string TransformEmojis(string message)
        {
            #region Emoji Collection
            var htEmoji = new Hashtable
                {
                    { ":statue_of_liberty:", "statue_of_liberty.png" },
                    { ":dolls:", "dolls.png" },
                    { ":flushed:", "flushed.png" },
                    { ":house:", "house.png" },
                    { ":trumpet:", "trumpet.png" },
                    { ":ocean:", "ocean.png" },
                    { ":busstop:", "busstop.png" },
                    { ":ru:", "ru.png" },
                    { ":crown:", "crown.png" },
                    { ":bank:", "bank.png" },
                    { ":rice:", "rice.png" },
                    { ":red_circle:", "red_circle.png" },
                    { ":rage:", "rage.png" },
                    { ":eight_spoked_asterisk:", "eight_spoked_asterisk.png" },
                    { ":dress:", "dress.png" },
                    { ":sagittarius:", "sagittarius.png" },
                    { ":birthday:", "birthday.png" },
                    { ":mount_fuji:", "mount_fuji.png" },
                    { ":police_car:", "police_car.png" },
                    { ":musical_note:", "musical_note.png" },
                    { ":dancers:", "dancers.png" },
                    { ":thumbsup:", "thumbsup.png" },
                    { ":ok_hand:", "ok_hand.png" },
                    { ":feelsgood:", "feelsgood.png" },
                    { ":cold_sweat:", "cold_sweat.png" },
                    { ":gem:", "gem.png" },
                    { ":tulip:", "tulip.png" },
                    { ":grey_question:", "grey_question.png" },
                    { ":palm_tree:", "palm_tree.png" },
                    { ":microphone:", "microphone.png" },
                    { ":new:", "new.png" },
                    { ":monkey_face:", "monkey_face.png" },
                    { ":yellow_heart:", "yellow_heart.png" },
                    { ":haircut:", "haircut.png" },
                    { ":information_desk_person:", "information_desk_person.png" },
                    { ":cool:", "cool.png" },
                    { ":bus:", "bus.png" },
                    { ":octopus:", "octopus.png" },
                    { ":fast_forward:", "fast_forward.png" },
                    { ":punch:", "punch.png" },
                    { ":ear:", "ear.png" },
                    { ":astonished:", "astonished.png" },
                    { ":speaker:", "speaker.png" },
                    { ":star2:", "star2.png" },
                    { ":goberserk:", "goberserk.png" },
                    { ":loudspeaker:", "loudspeaker.png" },
                    { ":bullettrain_front:", "bullettrain_front.png" },
                    { ":oden:", "oden.png" },
                    { ":tokyo_tower:", "tokyo_tower.png" },
                    { ":person_with_blond_hair:", "person_with_blond_hair.png" },
                    { ":guardsman:", "guardsman.png" },
                    { ":smirk:", "smirk.png" },
                    { ":tea:", "tea.png" },
                    { ":basketball:", "basketball.png" },
                    { ":ophiuchus:", "ophiuchus.png" },
                    { ":hamster:", "hamster.png" },
                    { ":unlock:", "unlock.png" },
                    { ":penguin:", "penguin.png" },
                    { ":tophat:", "tophat.png" },
                    { ":red_car:", "red_car.png" },
                    { ":chicken:", "chicken.png" },
                    { ":surfer:", "surfer.png" },
                    { ":shell:", "shell.png" },
                    { ":dart:", "dart.png" },
                    { ":headphones:", "headphones.png" },
                    { ":bell:", "bell.png" },
                    { ":fr:", "fr.png" },
                    { ":arrow_upper_left:", "arrow_upper_left.png" },
                    { ":mens:", "mens.png" },
                    { ":postbox:", "postbox.png" },
                    { ":apple:", "apple.png" },
                    { ":womans_hat:", "womans_hat.png" },
                    { ":parking:", "parking.png" },
                    { ":art:", "art.png" },
                    { ":clock1:", "clock1.png" },
                    { ":city_sunset:", "city_sunset.png" },
                    { ":tiger:", "tiger.png" },
                    { ":fearful:", "fearful.png" },
                    { ":construction_worker:", "construction_worker.png" },
                    { ":signal_strength:", "signal_strength.png" },
                    { ":clock2:", "clock2.png" },
                    { ":white_square:", "white_square.png" },
                    { ":kr:", "kr.png" },
                    { ":cancer:", "cancer.png" },
                    { ":trophy:", "trophy.png" },
                    { ":hankey:", "hankey.png" },
                    { ":clock3:", "clock3.png" },
                    { ":princess:", "princess.png" },
                    { ":mega:", "mega.png" },
                    { ":clock4:", "clock4.png" },
                    { ":bouquet:", "bouquet.png" },
                    { ":vibration_mode:", "vibration_mode.png" },
                    { ":up:", "up.png" },
                    { ":ok_woman:", "ok_woman.png" },
                    { ":clock5:", "clock5.png" },
                    { ":nail_care:", "nail_care.png" },
                    { ":wink2:", "wink2.png" },
                    { ":aries:", "aries.png" },
                    { ":rocket:", "rocket.png" },
                    { ":clock6:", "clock6.png" },
                    { ":mask:", "mask.png" },
                    { ":thumbsdown:", "thumbsdown.png" },
                    { ":santa:", "santa.png" },
                    { ":clock7:", "clock7.png" },
                    { ":godmode:", "godmode.png" },
                    { ":gift:", "gift.png" },
                    { ":persevere:", "persevere.png" },
                    { ":clock8:", "clock8.png" },
                    { ":tent:", "tent.png" },
                    { ":womens:", "womens.png" },
                    { ":tada:", "tada.png" },
                    { ":us:", "us.png" },
                    { ":clock9:", "clock9.png" },
                    { ":older_woman:", "older_woman.png" },
                    { ":whale:", "whale.png" },
                    { ":ideograph_advantage:", "ideograph_advantage.png" },
                    { ":traffic_light:", "traffic_light.png" },
                    { ":radio:", "radio.png" },
                    { ":four_leaf_clover:", "four_leaf_clover.png" },
                    { ":de:", "de.png" },
                    { ":six_pointed_star:", "six_pointed_star.png" },
                    { ":no_smoking:", "no_smoking.png" },
                    { ":rage1:", "rage1.png" },
                    { ":iphone:", "iphone.png" },
                    { ":sandal:", "sandal.png" },
                    { ":fountain:", "fountain.png" },
                    { ":id:", "id.png" },
                    { ":rage2:", "rage2.png" },
                    { ":baseball:", "baseball.png" },
                    { ":ferris_wheel:", "ferris_wheel.png" },
                    { ":slot_machine:", "slot_machine.png" },
                    { ":bread:", "bread.png" },
                    { ":rage3:", "rage3.png" },
                    { ":ear_of_rice:", "ear_of_rice.png" },
                    { ":virgo:", "virgo.png" },
                    { ":top:", "top.png" },
                    { ":wink:", "wink.png" },
                    { ":rage4:", "rage4.png" },
                    { ":train:", "train.png" },
                    { ":purple_heart:", "purple_heart.png" },
                    { ":sa:", "sa.png" },
                    { ":muscle:", "muscle.png" },
                    { ":rice_scene:", "rice_scene.png" },
                    { ":checkered_flag:", "checkered_flag.png" },
                    { ":109:", "109.png" },
                    { ":o2:", "o2.png" },
                    { ":closed_umbrella:", "closed_umbrella.png" },
                    { ":no_good:", "no_good.png" },
                    { ":baby:", "baby.png" },
                    { ":cupid:", "cupid.png" },
                    { ":snake:", "snake.png" },
                    { ":eggplant:", "eggplant.png" },
                    { ":football:", "football.png" },
                    { ":email:", "email.png" },
                    { ":spaghetti:", "spaghetti.png" },
                    { ":bulb:", "bulb.png" },
                    { ":fire_engine:", "fire_engine.png" },
                    { ":joy:", "joy.png" },
                    { ":rabbit:", "rabbit.png" },
                    { ":heart:", "heart.png" },
                    { ":registered:", "registered.png" },
                    { ":high_heel:", "high_heel.png" },
                    { ":bird:", "bird.png" },
                    { ":fire:", "fire.png" },
                    { ":green_heart:", "green_heart.png" },
                    { ":cop:", "cop.png" },
                    { ":bullettrain_side:", "bullettrain_side.png" },
                    { ":clap:", "clap.png" },
                    { ":seat:", "seat.png" },
                    { ":maple_leaf:", "maple_leaf.png" },
                    { ":woman:", "woman.png" },
                    { ":sheep:", "sheep.png" },
                    { ":mahjong:", "mahjong.png" },
                    { ":moneybag:", "moneybag.png" },
                    { ":rice_cracker:", "rice_cracker.png" },
                    { ":toilet:", "toilet.png" },
                    { ":walking:", "walking.png" },
                    { ":beer:", "beer.png" },
                    { ":taxi:", "taxi.png" },
                    { ":jack_o_lantern:", "jack_o_lantern.png" },
                    { ":snowman:", "snowman.png" },
                    { ":church:", "church.png" },
                    { ":clock10:", "clock10.png" },
                    { ":feet:", "feet.png" },
                    { ":clubs:", "clubs.png" },
                    { ":clock11:", "clock11.png" },
                    { ":it:", "it.png" },
                    { ":cow:", "cow.png" },
                    { ":book:", "book.png" },
                    { ":metro:", "metro.png" },
                    { ":clock12:", "clock12.png" },
                    { ":copyright:", "copyright.png" },
                    { ":0:", "0.png" },
                    { ":pray:", "pray.png" },
                    { ":open_hands:", "open_hands.png" },
                    { ":trident:", "trident.png" },
                    { ":blush:", "blush.png" },
                    { ":notes:", "notes.png" },
                    { ":1:", "1.png" },
                    { ":frog:", "frog.png" },
                    { ":dancer:", "dancer.png" },
                    { ":arrow_up:", "arrow_up.png" },
                    { ":2:", "2.png" },
                    { ":massage:", "massage.png" },
                    { ":point_up:", "point_up.png" },
                    { ":3:", "3.png" },
                    { ":u6708:", "u6708.png" },
                    { ":pill:", "pill.png" },
                    { ":u6709:", "u6709.png" },
                    { ":4:", "4.png" },
                    { ":barber:", "barber.png" },
                    { ":taurus:", "taurus.png" },
                    { ":strawberry:", "strawberry.png" },
                    { ":5:", "5.png" },
                    { ":egg:", "egg.png" },
                    { ":sunrise_over_mountains:", "sunrise_over_mountains.png" },
                    { ":gb:", "gb.png" },
                    { ":blue_heart:", "blue_heart.png" },
                    { ":6:", "6.png" },
                    { ":post_office:", "post_office.png" },
                    { ":bath:", "bath.png" },
                    { ":7:", "7.png" },
                    { ":rice_ball:", "rice_ball.png" },
                    { ":heart_eyes:", "heart_eyes.png" },
                    { ":relieved:", "relieved.png" },
                    { ":shirt:", "shirt.png" },
                    { ":scream:", "scream.png" },
                    { ":koala:", "koala.png" },
                    { ":8:", "8.png" },
                    { ":boot:", "boot.png" },
                    { ":capricorn:", "capricorn.png" },
                    { ":sake:", "sake.png" },
                    { ":man_with_gua_pi_mao:", "man_with_gua_pi_mao.png" },
                    { ":beginner:", "beginner.png" },
                    { ":sob:", "sob.png" },
                    { ":9:", "9.png" },
                    { ":baby_symbol:", "baby_symbol.png" },
                    { ":squirrel:", "squirrel.png" },
                    { ":disappointed:", "disappointed.png" },
                    { ":dash:", "dash.png" },
                    { ":grey_exclamation:", "grey_exclamation.png" },
                    { ":sweat_drops:", "sweat_drops.png" },
                    { ":congratulations:", "congratulations.png" },
                    { ":fireworks:", "fireworks.png" },
                    { ":handbag:", "handbag.png" },
                    { ":metal:", "metal.png" },
                    { ":skull:", "skull.png" },
                    { ":briefcase:", "briefcase.png" },
                    { ":shipit:", "shipit.png" },
                    { ":ring:", "ring.png" },
                    { ":bomb:", "bomb.png" },
                    { ":hand:", "hand.png" },
                    { ":lipstick:", "lipstick.png" },
                    { ":bike:", "bike.png" },
                    { ":spades:", "spades.png" },
                    { ":curry:", "curry.png" },
                    { ":stew:", "stew.png" },
                    { ":arrow_upper_right:", "arrow_upper_right.png" },
                    { ":koko:", "koko.png" },
                    { ":mortar_board:", "mortar_board.png" },
                    { ":hotsprings:", "hotsprings.png" },
                    { ":u55b6:", "u55b6.png" },
                    { ":heartpulse:", "heartpulse.png" },
                    { ":flags:", "flags.png" },
                    { ":couplekiss:", "couplekiss.png" },
                    { ":school_satchel:", "school_satchel.png" },
                    { ":arrow_forward:", "arrow_forward.png" },
                    { ":leaves:", "leaves.png" },
                    { ":gun:", "gun.png" },
                    { ":wedding:", "wedding.png" },
                    { ":moon:", "moon.png" },
                    { ":older_man:", "older_man.png" },
                    { ":swimmer:", "swimmer.png" },
                    { ":point_right:", "point_right.png" },
                    { ":hash:", "hash.png" },
                    { ":tomato:", "tomato.png" },
                    { ":cake:", "cake.png" },
                    { ":gemini:", "gemini.png" },
                    { ":kiss:", "kiss.png" },
                    { ":secret:", "secret.png" },
                    { ":elephant:", "elephant.png" },
                    { ":kissing_heart:", "kissing_heart.png" },
                    { ":hospital:", "hospital.png" },
                    { ":arrow_lower_right:", "arrow_lower_right.png" },
                    { ":love_hotel:", "love_hotel.png" },
                    { ":wheelchair:", "wheelchair.png" },
                    { ":sunrise:", "sunrise.png" },
                    { ":phone:", "phone.png" },
                    { ":rewind:", "rewind.png" },
                    { ":u6307:", "u6307.png" },
                    { ":leo:", "leo.png" },
                    { ":-1:", "-1.png" },
                    { ":airplane:", "airplane.png" },
                    { ":fork_and_knife:", "fork_and_knife.png" },
                    { ":stars:", "stars.png" },
                    { ":school:", "school.png" },
                    { ":soccer:", "soccer.png" },
                    { ":bikini:", "bikini.png" },
                    { ":cry:", "cry.png" },
                    { ":sunflower:", "sunflower.png" },
                    { ":fuelpump:", "fuelpump.png" },
                    { ":dolphin:", "dolphin.png" },
                    { ":clapper:", "clapper.png" },
                    { ":sailboat:", "sailboat.png" },
                    { ":mag:", "mag.png" },
                    { ":speedboat:", "speedboat.png" },
                    { ":vs:", "vs.png" },
                    { ":scissors:", "scissors.png" },
                    { ":arrow_lower_left:", "arrow_lower_left.png" },
                    { ":blue_car:", "blue_car.png" },
                    { ":department_store:", "department_store.png" },
                    { ":icecream:", "icecream.png" },
                    { ":cactus:", "cactus.png" },
                    { ":ambulance:", "ambulance.png" },
                    { ":wolf:", "wolf.png" },
                    { ":smile:", "smile.png" },
                    { ":angel:", "angel.png" },
                    { ":ship:", "ship.png" },
                    { ":sweat:", "sweat.png" },
                    { ":sleepy:", "sleepy.png" },
                    { ":raised_hands:", "raised_hands.png" },
                    { ":tennis:", "tennis.png" },
                    { ":baby_chick:", "baby_chick.png" },
                    { ":suspect:", "suspect.png" },
                    { ":arrow_right:", "arrow_right.png" },
                    { ":man:", "man.png" },
                    { ":bow:", "bow.png" },
                    { ":city_sunrise:", "city_sunrise.png" },
                    { ":couple_with_heart:", "couple_with_heart.png" },
                    { ":pencil:", "pencil.png" },
                    { ":unamused:", "unamused.png" },
                    { ":car:", "car.png" },
                    { ":shit:", "shit.png" },
                    { ":anger:", "anger.png" },
                    { ":sparkler:", "sparkler.png" },
                    { ":mouse:", "mouse.png" },
                    { ":sparkles:", "sparkles.png" },
                    { ":cat:", "cat.png" },
                    { ":boy:", "boy.png" },
                    { ":rainbow:", "rainbow.png" },
                    { ":crossed_flags:", "crossed_flags.png" },
                    { ":bowtie:", "bowtie.png" },
                    { ":chart:", "chart.png" },
                    { ":hotel:", "hotel.png" },
                    { ":question:", "question.png" },
                    { ":movie_camera:", "movie_camera.png" },
                    { ":bamboo:", "bamboo.png" },
                    { ":wind_chime:", "wind_chime.png" },
                    { ":grin:", "grin.png" },
                    { ":pensive:", "pensive.png" },
                    { ":point_left:", "point_left.png" },
                    { ":couple:", "couple.png" },
                    { ":computer:", "computer.png" },
                    { ":cyclone:", "cyclone.png" },
                    { ":cocktail:", "cocktail.png" },
                    { ":shaved_ice:", "shaved_ice.png" },
                    { ":coffee:", "coffee.png" },
                    { ":cloud:", "cloud.png" },
                    { ":memo:", "memo.png" },
                    { ":point_down:", "point_down.png" },
                    { ":currency_exchange:", "currency_exchange.png" },
                    { ":rose:", "rose.png" },
                    { ":eyes:", "eyes.png" },
                    { ":space_invader:", "space_invader.png" },
                    { ":ok:", "ok.png" },
                    { ":imp:", "imp.png" },
                    { ":hamburger:", "hamburger.png" },
                    { ":alien:", "alien.png" },
                    { ":fish:", "fish.png" },
                    { ":christmas_tree:", "christmas_tree.png" },
                    { ":bear:", "bear.png" },
                    { ":u7121:", "u7121.png" },
                    { ":jp:", "jp.png" },
                    { ":golf:", "golf.png" },
                    { ":ticket:", "ticket.png" },
                    { ":confounded:", "confounded.png" },
                    { ":eight_pointed_black_star:", "eight_pointed_black_star.png" },
                    { ":es:", "es.png" },
                    { ":point_up_2:", "point_up_2.png" },
                    { ":necktie:", "necktie.png" },
                    { ":camel:", "camel.png" },
                    { ":libra:", "libra.png" },
                    { ":fries:", "fries.png" },
                    { ":dvd:", "dvd.png" },
                    { ":european_castle:", "european_castle.png" },
                    { ":boar:", "boar.png" },
                    { ":tm:", "tm.png" },
                    { ":loop:", "loop.png" },
                    { ":a:", "a.png" },
                    { ":cinema:", "cinema.png" },
                    { ":watermelon:", "watermelon.png" },
                    { ":finnadie:", "finnadie.png" },
                    { ":runner:", "runner.png" },
                    { ":beers:", "beers.png" },
                    { ":b:", "b.png" },
                    { ":nose:", "nose.png" },
                    { ":+1:", "+1.png" },
                    { ":balloon:", "balloon.png" },
                    { ":mailbox:", "mailbox.png" },
                    { ":boat:", "boat.png" },
                    { ":pisces:", "pisces.png" },
                    { ":tangerine:", "tangerine.png" },
                    { ":heartbeat:", "heartbeat.png" },
                    { ":sushi:", "sushi.png" },
                    { ":part_alternation_mark:", "part_alternation_mark.png" },
                    { ":tshirt:", "tshirt.png" },
                    { ":zap:", "zap.png" },
                    { ":fax:", "fax.png" },
                    { ":smoking:", "smoking.png" },
                    { ":cd:", "cd.png" },
                    { ":smiley:", "smiley.png" },
                    { ":wave:", "wave.png" },
                    { ":hammer:", "hammer.png" },
                    { ":mobile_phone_off:", "mobile_phone_off.png" },
                    { ":station:", "station.png" },
                    { ":sunny:", "sunny.png" },
                    { ":tv:", "tv.png" },
                    { ":fist:", "fist.png" },
                    { ":star:", "star.png" },
                    { ":fallen_leaf:", "fallen_leaf.png" },
                    { ":truck:", "truck.png" },
                    { ":arrow_backward:", "arrow_backward.png" },
                    { ":broken_heart:", "broken_heart.png" },
                    { ":u7a7a:", "u7a7a.png" },
                    { ":vhs:", "vhs.png" },
                    { ":diamonds:", "diamonds.png" },
                    { ":octocat:", "octocat.png" },
                    { ":poop:", "poop.png" },
                    { ":racehorse:", "racehorse.png" },
                    { ":calling:", "calling.png" },
                    { ":lock:", "lock.png" },
                    { ":o:", "o.png" },
                    { ":guitar:", "guitar.png" },
                    { ":bento:", "bento.png" },
                    { ":heart_decoration:", "heart_decoration.png" },
                    { ":roller_coaster:", "roller_coaster.png" },
                    { ":hurtrealbad:", "hurtrealbad.png" },
                    { ":ski:", "ski.png" },
                    { ":ghost:", "ghost.png" },
                    { ":8ball:", "8ball.png" },
                    { ":exclamation:", "exclamation.png" },
                    { ":japanese_castle:", "japanese_castle.png" },
                    { ":horse:", "horse.png" },
                    { ":tropical_fish:", "tropical_fish.png" },
                    { ":wc:", "wc.png" },
                    { ":camera:", "camera.png" },
                    { ":dango:", "dango.png" },
                    { ":cn:", "cn.png" },
                    { ":arrow_left:", "arrow_left.png" },
                    { ":arrow_down:", "arrow_down.png" },
                    { ":atm:", "atm.png" },
                    { ":construction:", "construction.png" },
                    { ":kissing_face:", "kissing_face.png" },
                    { ":black_square:", "black_square.png" },
                    { ":syringe:", "syringe.png" },
                    { ":restroom:", "restroom.png" },
                    { ":gift_heart:", "gift_heart.png" },
                    { ":relaxed:", "relaxed.png" },
                    { ":dissapointed:", "dissapointed.png" },
                    { ":part_alertnation_mark:", "part_alertnation_mark.png" },
                    { ":factory:", "factory.png" },
                    { ":underage:", "underage.png" },
                    { ":v:", "v.png" },
                    { ":ramen:", "ramen.png" },
                    { ":office:", "office.png" },
                    { ":convenience_store:", "convenience_store.png" },
                    { ":x:", "x.png" },
                    { ":dog:", "dog.png" },
                    { ":minidisc:", "minidisc.png" },
                    { ":pig:", "pig.png" },
                    { ":monkey:", "monkey.png" },
                    { ":key:", "key.png" },
                    { ":telephone:", "telephone.png" },
                    { ":tongue:", "tongue.png" },
                    { ":aquarius:", "aquarius.png" },
                    { ":u7533:", "u7533.png" },
                    { ":umbrella:", "umbrella.png" },
                    { ":bug:", "bug.png" },
                    { ":hibiscus:", "hibiscus.png" },
                    { ":shoe:", "shoe.png" },
                    { ":man_with_turban:", "man_with_turban.png" },
                    { ":lips:", "lips.png" },
                    { ":satellite:", "satellite.png" },
                    { ":kimono:", "kimono.png" },
                    { ":scorpius:", "scorpius.png" },
                    { ":saxophone:", "saxophone.png" },
                    { ":u5272:", "u5272.png" },
                    { ":warning:", "warning.png" },
                    { ":angry:", "angry.png" },
                    { ":u6e80:", "u6e80.png" },
                    { ":satisfied:", "satisfied.png" },
                    { ":cherry_blossom:", "cherry_blossom.png" },
                    { ":zzz:", "zzz.png" },
                    { ":ab:", "ab.png" },
                    { ":girl:", "girl.png" }
                };
            #endregion

            var sbMessage = new StringBuilder(message);

            foreach (var emote in htEmoji.Keys.Cast<string>())
            {
                sbMessage.Replace(emote, string.Format("<img src=\"/Content/images/emojis/{0}\" alt=\"{1}\" title=\"{1}\" height=\"20\" width=\"20\" align=\"absmiddle\" />", htEmoji[emote], emote));
            }

            return sbMessage.ToString();
        }
    }
}